micronaut:
  application:
    name: ${project.artifactId}

  server:
    port: 7070

  metrics:
    enabled: true
    export:
      prometheus:
        step: PT2s
        descriptions: false

  http:
    services:
      read-timeout: 30s
      ngsi:
        path: ngsi-ld/v1
        url: http://localhost:1026
        read-timeout: 30
      canis-major:
        path: /
        url: http://localhost:4000
        read-timeout: 30

---
endpoints:
  metrics:
    enabled: true
  health:
    enabled: true
  info:
    enabled: true
    sensitive: false

---
loggers:
  levels:
    ROOT: TRACE

---
general:
  contextUrl: https://smartdatamodels.org/context.jsonld